# Generated by Django 4.1.4 on 2022-12-17 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='製品名')),
                ('max_price', models.IntegerField(verbose_name='最高価格')),
                ('min_price', models.IntegerField(verbose_name='最低価格')),
                ('product_price', models.IntegerField(verbose_name='値段')),
                ('price_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='値段の重み')),
                ('max_size', models.IntegerField(verbose_name='最高サイズ')),
                ('min_size', models.IntegerField(verbose_name='最低サイズ')),
                ('product_size', models.IntegerField(verbose_name='サイズ')),
                ('size_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='サイズの重み')),
                ('max_memory', models.IntegerField(verbose_name='最高メモリ')),
                ('min_memory', models.IntegerField(verbose_name='最低メモリ')),
                ('product_memory', models.IntegerField(verbose_name='メモリ')),
                ('memory_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='メモリの重み')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
