# Generated by Django 4.1.4 on 2022-12-18 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='memory_weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='メモリの重み(%)'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='price_weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='価格の重み(%)'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='size_weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='サイズの重み(%)'),
        ),
    ]
